### PR TITLE
disable precompilation on windows

### PR DESCRIPTION
**Pull request by tkelman**
may help with the RegistryKeyLookupFailed `CoderModulesPath' error?

### CODE REVIEW

**Comment by timholy** [comment]
Yay, thanks a bunch!

**Comment by timholy** [comment]
(Bummer, of course.)

**Comment by timholy** [comment]
Hmm, just saw https://github.com/JuliaLang/julia/issues/12638. Once that's available, we might try reverting this?

**Comment by tkelman** [comment]
The commit that ran, at least on win32, was https://github.com/JuliaLang/julia/commit/6becc96 so would have had that fix. win64 said it was running on https://github.com/JuliaLang/julia/commit/58408ff which is a bit confusing since that was a commit from inside a PR? Anyway good reason to always have `versioninfo()` somewhere in the CI logs.

Can always try reverting this periodically and see if it helps. I suspect trying the WinRPM version of imagemagick may be more effective though, if the current library is trying to access something from the registry in its initialization? Maybe unfixable though, I'm not really sure.

**Comment by flicaflow** [comment]
I just enabled precompilation manually on Windows for the Images package. I do not see any errors, tests are succeeding . Maybe this change could be reverted?

**Comment by SimonDanisch** [comment]
I did that as well on my fileio branch... Seems to work fine for my use cases as well!

**Comment by timholy** [comment]
Keep an eye on #358 and we'll see how it goes.

**Pull request merged**
