### PR TITLE
Fix Version checking for chkbounds

### PR DESCRIPTION
**Pull request by mronian**
Refer https://github.com/timholy/Images.jl/commit/4cd185c5d977dc0632239f9f62ca779f358f0640#commitcomment-18546910

### CODE REVIEW

**Comment by timholy** [comment]
I think the actual number is `0.5.0-dev+4697`, see https://github.com/JuliaLang/julia/commit/9ee611260006346daf5145569f1225b7d2f401d2.

**Comment by timholy** [comment]
Or rather, 4754 (the merge commit).

**Comment by mronian** [comment]
@timholy I have changed the version to 4754.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
