### PR TITLE
modified:   src/algorithms.jl:328 sumsq->abs2

### PR DESCRIPTION
**Pull request by hustf**
Removes Pkg.test deprecation warning.

### CODE REVIEW

**Comment by kmsquire** [comment]
Personally, I think I'd rather this be renamed in Base to `sumsq`.

**Comment by timholy** [comment]
I think it used to be `sumsq`, and got changed to `abs2`. In this case it's being used on a scalar, so the `sum` part of that name would indeed have been confusing.

**Comment by timholy** [comment]
Thanks!

**Comment by kmsquire** [comment]
(That's what happens when I don't actually read the PR.  Sorry for any confusion!)

**Pull request merged**
