### PR TITLE
Faster histeq

### PR DESCRIPTION
**Pull request by timholy**
Ref https://github.com/timholy/Images.jl/pull/523#issuecomment-235236460, CC @mronian.

### CODE REVIEW

**Comment by timholy** [comment]
Since I had this already I thought it would be best to just submit it. But a little bit of poking around suggests that `histmatch` may have the same performance problem, so a good exercise for you :smile: will be to check that it's indeed a problem and fix it.

**Comment by mronian** [comment]
@timholy I tried the same with ```histmatch``` and ```adjust_gamma``` but there seems to be no increase in speed. ```ProfileVIew.view(C=true)``` does not have the internal C function calls or ```typemap``` at the top of the stack like in ```histeq```. Still, should we avoid map just to be safe?

**Comment by mronian** [comment]
Turns out not only ```map``` but any type of ```[do this for i in I]``` type of statement causes speed issues. I changed - 
```jl
table = [T((i / typemax(raw_type)) ^ gamma_inv) for i in zero(raw_type):typemax(raw_type)]
```
to - 
```jl
table = zeros(Float64, typemax(raw_type) + 1)
    for i in zero(raw_type):typemax(raw_type)
        table[i + 1] = T((i / typemax(raw_type)) ^ gamma_inv)
    end
```
in ```adjust_gamma``` and the speed up is incredible.

**Comment by timholy** [comment]
Great, glad to hear it! (Or in a sense, sorry to hear it---would be nice if the original worked just as well. But worthwhile improvements for users.)

**Pull request merged**
