### PR TITLE
Use relative paths instead of Pkg.dir("Images")

### PR DESCRIPTION
**Pull request by tkelman**
this allows installing in a non-default location

ref https://github.com/JuliaLang/julia/issues/8679#issuecomment-75796502

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, the version of ImageMagick on Travis seems to have a transparency bug. And AppVeyor seems to be finicky about redefining writedir. At least the latter is something I can fix.

**Comment by timholy** [comment]
Have you tested this on your machine?

**Comment by swt30** [comment]
I just cherry-picked this commit onto v0.4.21 and tested on my machine with a standard install path - no problems there.

**Comment by tkelman** [comment]
It appears to work fine in the standard install path on Linux and Windows. Have not tested installing outside of `Pkg.dir` but I believe this could only help in that scenario.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
