### PR TITLE
Update Windows binary URL, enable AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**
I can squash these if you'd prefer.

Might be good to turn on a nightly build of this too like we did for HDF5, as long as the queue's not getting too long on your AppVeyor account.

Results should be at https://ci.appveyor.com/project/tkelman/images-jl/build/1.0.4, will see

### CODE REVIEW

**Comment by tkelman** [comment]
That installed correctly, though the tests don't pass. Win32 fails due to an issue in SIUnits.jl (cc @Keno):
```
ERROR: `+` has no method matching +(::(Int32,Int32,Int32,Int32,Int32,Int32,Int32), ::(Int32,Int32,Int32,Int32,Int32,Int32,Int32))
 in * at promotion.jl:159
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:66
 in require at loading.jl:51
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:349
while loading C:\Users\appveyor\.julia\v0.3\SIUnits\src\SIUnits.jl, in expression starting on line 292
while loading C:\Users\appveyor\.julia\v0.3\Images\test\core.jl, in expression starting on line 1
while loading C:\Users\appveyor\.julia\v0.3\Images\test\runtests.jl, in expression starting on line 2
```

And Win64 hits
```
ERROR: libversion not defined
 in image2wand at C:\Users\appveyor\.julia\v0.3\Images\src\io.jl:319
 in writemime at C:\Users\appveyor\.julia\v0.3\Images\src\io.jl:204
 in anonymous at C:\Users\appveyor\.julia\v0.3\Images\test\io.jl:51
```

**Comment by timholy** [comment]
This is awesome! No need to squash.

The `libversion` error is interesting. It indicates that there's [something wrong](https://github.com/timholy/Images.jl/blob/4670011d0ce91dc23440a169a8f2242133692c3c/src/ioformats/libmagickwand.jl#L27-L35) during the [build process](https://github.com/timholy/Images.jl/blob/4670011d0ce91dc23440a169a8f2242133692c3c/deps/build.jl#L78-L90). The thing I find surprising is that I don't see any indication of failure during the build process.

Presumably the best thing would be to merge this, and then start a PR that produces debugging output during the version test? (Or, if you want to try adding that to this PR, be my guest.)

**Comment by tkelman** [comment]
I can try to debug in a separate branch on my fork.

**Comment by tkelman** [comment]
On a local machine I get an entirely different error on Win64:
```
julia> @time Pkg.test("Images")
INFO: Testing Images
ERROR: key not found: 15
 in imread at C:\Users\MPC_CAR\.julia\v0.3\Images\src\io.jl:261
 in imread at C:\Users\MPC_CAR\.julia\v0.3\Images\src\io.jl:114
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354
while loading C:\Users\MPC_CAR\.julia\v0.3\Images\test\io.jl, in expression star
ting on line 27
while loading C:\Users\MPC_CAR\.julia\v0.3\Images\test\runtests.jl, in expressio
n starting on line 5
```

**Comment by tkelman** [comment]
Hah. Looks like the `versioninfo.jl` file is ending up in the `deps/downloads` folder. Probably want to switch to an absolute path there.

**Comment by tkelman** [comment]
After that change I do still get `ERROR: key not found: 15` and I expect AppVeyor will too for win64 in a few minutes: https://ci.appveyor.com/project/tkelman/images-jl/build/1.0.7/job/xo3btu2ucoeaxvcd

**Comment by timholy** [comment]
I never heard of a 15-bit image. But I can fix that. This is great stuff, thanks for doing this!

**Comment by tkelman** [comment]
my pleasure as always

**Pull request merged**
