### PR TITLE
Fix tests for scalar index change on 0.5

### PR DESCRIPTION
**Pull request by yuyichao**
This is the bare minimum change to make the tests pass. I think there shouldn't be much (any?) others that needs updating given `Images` mostly delegate to the base version for indexing.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks, @yuyichao! Since this is on your own fork, can I ask you to also remove the comments from [this line](https://github.com/timholy/Images.jl/blob/4594c7363e9fba30e1befa5f8e0c5fec56cf746f/.travis.yml#L7) and [this one](https://github.com/timholy/Images.jl/blob/4594c7363e9fba30e1befa5f8e0c5fec56cf746f/appveyor.yml#L5-L6) so the tests get run on 0.5?

**Comment by yuyichao** [comment]
Ahh, I didn't check that. Sure.

**Comment by yuyichao** [comment]
Done and tests all passed.

P.S. I like this PR number, even though apparently no one can find it. ;-p.

**Comment by timholy** [comment]
:smile:

Thanks. You're doing great stuff over a wide swath of julia, and we are all grateful.

**Pull request merged**
