### PR TITLE
Fixes #488

### LINKED ISSUE #488: Error during compilation
```using Images``` gives the following error :

```
ERROR: LoadError: LoadError: MethodError: no method matching Symbol(::ASCIIString, ::Int64)
Closest candidates are:
  (::Type{BoundsError})(::ANY, ::ANY)
  (::Type{TypeError})(::Any, ::Any, ::Any, ::Any)
  (::Type{TypeConstructor})(::ANY, ::ANY)
  ...
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:267
 [inlined code] from ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jarvis/.julia/v0.5/Images/src/overlays.jl, in expression starting on line 70
while loading /home/jarvis/.julia/v0.5/Images/src/Images.jl, in expression starting on line 40
ERROR: Failed to precompile Images to /home/jarvis/.julia/lib/v0.5/Images.ji
 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in compilecache(::Symbol) at ./loading.jl:485
 in require(::Symbol) at ./loading.jl:355
 in eval(::Module, ::Any) at ./boot.jl:267
```

I localised it to the the following PR #483.

### PR DESCRIPTION
**Pull request by mronian**

### CODE REVIEW

**Comment by timholy** [comment]
Just for my information, which julia version are you using? The original works for me.

**Comment by mronian** [comment]
The version is "0.5.0-dev+3145".

**Comment by timholy** [comment]
Seems to work in `0.5.0-dev+4255`.

**Comment by mronian** [comment]
My bad. I have updated my version now.

**Comment by timholy** [comment]
No problem. Knowing whether something is supposed to work or not is not easy.

**Pull request closed without merging**
