### PR TITLE
Add @test_approx_eq_sigma_eps for approximate image testing

### PR DESCRIPTION
**Pull request by timholy**
CC @tbreloff

### CODE REVIEW

**Comment by tbreloff** [comment]
Cool!

**Comment by tbreloff** [comment]
Should I copy/paste this code into Plots for now?  I see the PR is still open, and I'd prefer not to have to track this branch to use it.  Thanks!

**Comment by timholy** [comment]
Thanks for the reminder, I forgot all about it.

**Comment by tbreloff** [comment]
Cool thanks! Now I have to actually write some tests...

**Comment by tbreloff** [comment]
I'm just starting to put some test code together... do you have any guidelines as to how I might set sigma/eps?

**Comment by timholy** [comment]
Nothing special. I'd personally set them to zero until I start seeing test failures, then study the specific failure. Once I understand the reason for the failure (small intensity change? slight change in antialiasing that leads to blurring?) then I'd have a principled choice.

That said, it sounds hard to go wrong blurring by a single pixel. The `eps` threshold is much harder to guess generically.

**Pull request merged**
