### PR TITLE
Docstrings!

### PR DESCRIPTION
**Pull request by timholy**
```
julia> using Images

help?> separate
search: separate

  imgs = separate(img) separates the color channels of img, for example returning an m-by-n-by-3 array from an m-by-n array of RGB.
```

This is a WIP because there are still many files to go, but I wanted to post this here now because of one concern: presumably it would be best to generate the [function reference](http://timholy.github.io/Images.jl/function_reference.html) from the docstrings. I haven't plumbed into the guts of the new documentation system, so: does anyone know how to do this?

Particular CC to @rsrock, since he invested a lot in the github.io docs.

### CODE REVIEW

**Comment by timholy** [comment]
I also disabled testing on nightly, since that's failing now and will keep doing so until the differences in slicing behavior get sorted out. (My lab has lobbied for staying with 0.4 for as long as possible, so it seems unlikely that I'll put a lot of effort into following 0.5.)

**Comment by vchuravy** [comment]
:clap: 

and I think staying with 0.4 is fine for now.

**Comment by rsrock** [comment]
Nice!  I'll look into integrating this with the rest of the manual.  It seems like there's a way to generate the function reference sections automatically.

**Comment by timholy** [comment]
My favorite part of this: if you forget what function you're looking for, now you can do this:
```jl
  help?> Images

  Images is a package for representing and processing images.

  Constructors, conversions, and traits:

  - Construction: `Image`, `ImageCmap`, `grayim`, `colorim`, `convert`, `copyproperties`, `shareproperties`
  - Traits: `colordim`, `colorspace`, `coords_spatial`, `data`, `isdirect`, `isxfirst`, `isyfirst`, `pixelspacing`, `properties`, `sdims`, `spacedirections`, `spatialorder`, `storageorder`, `timedim`
  - Size-related traits: `height`, `nchannels`, `ncolorelem`, `nimages`, `size_spatial`, `width`, `widthheight`
  - Trait assertions: `assert_2d`, `assert_scalar_color`, `assert_timedim_last`, `assert_xfirst`, `assert_yfirst`
  - Indexing operations: `getindexim`, `sliceim`, `subim`
  - Conversions: `convert`, `raw`, `reinterpret`, `separate`

  Contrast/coloration:

  - `MapInfo`: `MapNone`, `BitShift`, `ClampMinMax`, `ScaleMinMax`, `ScaleAutoMinMax`, etc.
  - `imadjustintensity`, `sc`, `imstretch`, `imcomplement`

  Algorithms:

  - Reductions: `maxfinite`, `maxabsfinite`, `minfinite`, `meanfinite`, `sad`, `ssd`
  - Resizing: `restrict`, `imresize` (not yet exported)
  - Filtering: `imfilter`, `imfilter_fft`, `imfilter_gaussian`, `imfilter_LoG`, `imROF`, `ncc`, `padarray`
  - Filtering kernels: `ando[345]`, `guassian2d`, `imaverage`, `imdog`, `imlaplacian`, `prewitt`, `sobel`
  - Gradients: `backdiffx`, `backdiffy`, `forwarddiffx`, `forwarddiffy`, `imgradients`
  - Edge detection: `imedge`, `imgradients`, `thin_edges`, `magnitude`, `phase`, `magnitudephase`, `orientation`
  - Morphological operations: `dilate`, `erode`, `closing`, `opening`
  - Connected components: `label_components`

  Test images and phantoms (see also TestImages.jl):

  - `shepp_logan`
```

**Comment by lucasb-eyer** [comment]
:+1:

**Pull request merged**
