### PR TITLE
Fix for sub/slice->view

### PR DESCRIPTION
**Pull request by timholy**
Hopefully this will fix our tests (and Travis).

### CODE REVIEW

**Comment by bjarthur** [comment]
looks great.

what else needs to be done for julia 0.5?  i'm happy to help.

**Comment by timholy** [comment]
Thanks @bjarthur! I should resurrect the writemime deprecation PR and see if it works, but I'll do that after this merges. Would you perhaps check ImageMagick and see what needs to be done there? I'd like to make sure the tests pass and there aren't warnings, either when the package is built or during tests.

For Julia 0.5, I'm actually rewriting Images :smile:. Not very quickly because I've been consumed with Julia 0.5 contributions, but I just pushed [this](https://github.com/JuliaLang/julia/pull/17228) so perhaps I'll soon be free of my burdens :wink:.

**Comment by timholy** [comment]
Argh, by pulling in `StatsBase` (for the histogram functions) we've become dependent on Rmath, which is broken on Windows. Still, most tests pass, which is an improvement!

**Comment by timholy** [comment]
Oh, and @bjarthur, if you're taking requests...there's a warning thrown from Base.FFTW about `copy(::Tuple)`; it comes up in the Images "fft and ifft" tests. Almost surely leftover cruft from https://github.com/JuliaLang/julia/pull/15675. Since you've now made numerous base julia contributions, would you be willing to tackle that?

**Pull request merged**
