### PR TITLE
Added raw(img) to wrap the data out of UfixedBase, #190

### PR DESCRIPTION
**Pull request by cbecker**
This adds the raw(img) functionality, as discussed in #190

### CODE REVIEW

**Comment by timholy** [comment]
Can I ask that you add a couple of tests, too? In particular, it's worth checking this works for both grayscale and `RGB` images. It _should_ work because of https://github.com/timholy/Images.jl/blob/79eb3551b9c8dd06b414ba21a65b021ebd76354a/src/core.jl#L129-L162, but it's worth double-checking.

Adding documentation to https://github.com/timholy/Images.jl/blob/master/doc/function_reference.md and/or the README would be a bonus!

If you wait until https://github.com/JuliaLang/METADATA.jl/pull/2549 is merged, then the tests should pass again.

**Comment by timholy** [comment]
Actually, they may not pass due to https://github.com/JuliaLang/julia/issues/10513#issuecomment-99119291.

**Comment by cbecker** [comment]
sounds good, I will add tests and docs.

Currently I am avoiding julia v0.4, i'm afraid of having to spend too much time porting my code, as there are many code breaking changes.

**Comment by timholy** [comment]
Nothing you need to worry about here. While you don't have to test 0.4 locally, Travis tests it for you. I noticed it was broken, so dug into it and discovered SIUnits needed updating.

The parallel test (the last one) may still be broken on 0.4, however. Again, nothing you need to worry about.

**Comment by cbecker** [comment]
Hi Tim, I added the docs and some tests.
So far `raw()` expects an image as its argument, so it will throw an error if called with an array, for example. This contrasts with `data()`, shall we then define a fallback for arrays, as in `data()`?
```julia
julia> data(zeros((2,3)))
2x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> raw(zeros((2,3)))
ERROR: `raw` has no method matching raw(::Array{Float64,2})
```

**Comment by timholy** [comment]
Nice! Yes, I agree a fallback for arrays would be good. All you have to do is change the signature to `raw(img::AbstractArray)` and you should be good to go.

**Comment by cbecker** [comment]
Done, I rebased the PR as well.
I had to add a particular case for `raw([])`.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
