### PR TITLE
Fix depwarn on 0.5

### PR DESCRIPTION
**Pull request by yuyichao**
`ImageMagick.jl` PR coming soon. The only depwarn left comes from base https://github.com/JuliaLang/julia/pull/15675#issuecomment-214703355

### CODE REVIEW

**Comment by timholy** [comment]
Bless you, @yuyichao. I'll wait for CI, but this looks great.

**Comment by yuyichao** [comment]
There's some error on master that is not happening on my one week old build... I can have a look later.

**Comment by timholy** [comment]
I'll fix it.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
