### PR TITLE
imread: always use an even # of bits for ImageMagick

### PR DESCRIPTION
**Pull request by timholy**
This should fix https://github.com/timholy/Images.jl/pull/242#issuecomment-68817935. CC @tkelman.

### CODE REVIEW

**Comment by tkelman** [comment]
Hah, Travis no likey because apparently ImageMagick even moves their test images around...

**Comment by tkelman** [comment]
And I guess you need to enable the appveyor webhook for PR's, there's a checkbox on the github webhook settings to enable it for pull requests, under additional events IIRC

**Comment by timholy** [comment]
Actually the whole ImageMagick site is down. Let's wait a few hours and see what happens.

Alternatively, I could add these images to [`TestImages.jl`](https://github.com/timholy/TestImages.jl), and require that for testing. In `TestImages.jl` I've avoided committing the images to the repository (with one exception), but if flaky downloads are going to be a problem, perhaps I should just add them directly.

**Comment by timholy** [comment]
I hadn't added Images.jl to my AppVeyor projects list. I've done that now. Hopefully when I force-push this again it will work.

**Comment by tkelman** [comment]
Oh how strange, a build happened from merging the other PR https://ci.appveyor.com/project/timholy/images-jl/history so I thought you had already enabled it.

**Comment by tkelman** [comment]
that worked on win64, can you disable the SIUints tests when `Int == Int32`?

**Comment by tkelman** [comment]
sorry the `DownloadFile` line also had to change a little, I got it

**Comment by tkelman** [comment]
```
C:\projects\julia\bin\julia -e "Pkg.test(\"Images\")"
INFO: Testing Images
Warning: New definition 
    convert(Type{Images.Image{Cdest<:Union(Color.ColorValue{T},Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real}),N,A<:AbstractArray{T,N}}},Images.AbstractImageDirect{Csrc<:Union(Color.ColorValue{T},Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real}),N}) at C:\Users\appveyor\.julia\v0.4\Images\src\core.jl:228 
is ambiguous with: 
    convert(Type{Images.Image{T,N,A<:AbstractArray{T,N}}},Images.Image{T,N,A<:AbstractArray{T,N}}) at C:\Users\appveyor\.julia\v0.4\Images\src\core.jl:202.
To fix, define 
    convert(Type{Images.Image{_<:Union(Color.ColorValue{T},Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real}),N,A<:AbstractArray{T,N}}},Images.Image{_<:Union(Color.ColorValue{T},Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real}),N,A<:AbstractArray{T,N}}) 
before the new definition.
ERROR: test failed: ("RGB24" == "Gray")
 in expression: colorspace(B) == "Gray"
 in error at error.jl:21
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at no file
 in include_from_node1 at no file
 in include at no file
 in include_from_node1 at loading.jl:128
 in process_options at no file
 in _start at no file
while loading C:\Users\appveyor\.julia\v0.4\Images\test\core.jl, in expression starting on line 9
while loading C:\Users\appveyor\.julia\v0.4\Images\test\runtests.jl, in expression starting on line 4
```

**Comment by timholy** [comment]
Thanks!

I'm noting with some alarm those "0% coverage" notifications, given my recent changes to Coverage.jl. But I'm also noting that I haven't gotten coverage numbers for Images in a long time. I'll try to figure this out, but I have a dinner I need to be at.

**Comment by timholy** [comment]
Yay, @tkelman! Thanks again for turning this on.

**Comment by tkelman** [comment]
Cool, glad you were able to fix the issue!

**Pull request merged**
