### PR TITLE
Extensions of FileIO interface

### PR DESCRIPTION
**Pull request by timholy**
I excised ec2dec5, reverted the commit (#370) that caused the test failure, created some deprecations, and moved Imagine into its own package.

Only AndorSIF to go, right? Do you want me to tackle that?

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Awesome!!! 
`AndorSIF` is mostly ready and it might be better if you do the rest. I don't know the format and couldn't find any files to test this. I think it's fine to leave it in Images, as the other IO packages rely on Images anyways. Up to you ;)

**Comment by timholy** [comment]
OK. @rsrock, I'm going to take the liberty of moving the SIF reader over to JuliaIO, and make sure you have push privileges.

**Comment by timholy** [comment]
https://github.com/JuliaIO/AndorSIF.jl

Once this passes its tests, I'm merging :smile:.

**Comment by SimonDanisch** [comment]
Ha! That would be quite something :)
Just remembered though, that the reading `Vector{Uint8}` hasn't made it into ImageMagick.jl yet.
Are we forgetting other stuff?

**Comment by SimonDanisch** [comment]
Win64 0.3 is off by one:
```Julia
Expression: raw(res) --> raw(map(ScaleAutoMinMax(Ufixed16),raw(imgr))) 
Expected: 
Uint16[65535 43131
       49330 23688
       35780 41243]
Uint16[40516 36945
       43380 18967
       28964 0]
Occurred: 
Uint16[65535 43131
       49330 23688
       35780 41243]
Uint16[40516 36945
       43379 18967
       28964 0] 
```
This must be a rounding error due floating point precision problems?
Should we relax the test? Would be annoying if this lets the tests fail at random

**Comment by timholy** [comment]
I want to try to debug it first, so for now let's have it generate enough output to reproduce the problem.

**Comment by timholy** [comment]
The writemime test failure is expected until https://github.com/JuliaIO/FileIO.jl/pull/37 gets merged.

**Comment by rsrock** [comment]
No problem, I'll catch up with all these changes when I have the chance.  I assume osxnative is moving somewhere else too?  Let me know where that will go, I'd like to add image writing too.

I doubt that Andor SIF is used much. At one point I tried to grab a small test image, but it was with the wrong version of the software and the format was different. Of course.

--
Ronald S. Rock, Jr., Associate Professor  
Dept. of Biochemistry and Molecular Biology, The University of Chicago
GCIS W240, 929 E. 57th St.                                    
Chicago, IL 60637   USA
+1 773.702.0716 (w), +1 773.702.0439 (f)
rrock@uchicago.edu

**Comment by SimonDanisch** [comment]
Little checklist:
- [x] SIF 
- [x] Imagine
- [ ] pass PBM tests
- [x] writemime
- [ ] rounding (?) error
- [x] OSXNative
- [ ] OSXNative rename
- [x] NRRD
- [x] ImageMagick
- [ ]  merge `Choose a default for ambiguous` in FileIO

Probably incomplete ;)

**Comment by timholy** [comment]
OK, I think we're basically good to go here. This couples to the following PRs:
- https://github.com/JuliaIO/FileIO.jl/pull/38
- The new Netpbm package: https://github.com/JuliaIO/Netpbm.jl
- https://github.com/JuliaIO/ImageMagick.jl/pull/9

I think lots of travis tests will fail (surprisingly, this one succeeded) until packages are registered and tagged. OK to go ahead?

**Comment by timholy** [comment]
(I'm not sure what the "rounding error" means above.)

**Comment by SimonDanisch** [comment]
This one:
```Julia
Expression: raw(res) --> raw(map(ScaleAutoMinMax(Ufixed16),raw(imgr))) 
Expected: 
Uint16[65535 43131
       49330 23688
       35780 41243]
Uint16[40516 36945
       43380 18967
       28964 0]
Occurred: 
Uint16[65535 43131
       49330 23688
       35780 41243]
Uint16[40516 36945
       43379 18967
       28964 0] 
```

**Comment by timholy** [comment]
Ah, thanks for reminding me. Yes, let's wait for it to happen again and see what the debugging output tells us.

**Comment by timholy** [comment]
Aside from a [weird problem with QuartzImageIO](https://github.com/JuliaIO/QuartzImageIO.jl/pull/2), things are looking good. I'm interested in tagging a new (minor) release very soon. A key question: should Images (temporarily?) add
```
ImageMagick
@osx QuartzImageIO
```
to its REQUIRE file?

Also, if folks can test I'd be grateful.

**Comment by SimonDanisch** [comment]
Wow, is it Christmas already!? :)

**Comment by vchuravy** [comment]
:100: Whoo

**Comment by lucasb-eyer** [comment]
A `Pkg.update()`, followed by `Pkg.checkout("Images")` also installs `FileIO`. Subsequent `Pkg.test("Images")` succeeds. `imread("some.png")` nicely warns about deprecated `imread` and recommends `load`.

But with the new system, I'm back to having ImageMagick problems:

```
julia> load("/home/beyer/zealgo.png")
ERROR: ArgumentError: ImageMagick not found in path
 in require at ./loading.jl:233
 in check_loader at /home/beyer/.julia/v0.5/FileIO/src/loadsave.jl:11
```

A `Pkg.free("Images")` "fixes" this problem, e.g. `imread` works on my system in the latest release. I'll investigate this towards the end of the week.

**Comment by timholy** [comment]
Thanks for checking. Right now you have to say `Pkg.add("ImageMagick")`. See https://github.com/timholy/Images.jl/pull/373#issuecomment-144017692.

**Comment by lucasb-eyer** [comment]
Ah, right, I read that comment but comitted it to memory with a bitflip :) Adding the `ImageMagick` package, it all works fine on my Arch Linux for a few images I tried.

**Comment by timholy** [comment]
Awesome! Thanks for the report.

I think we can take this as evidence that we should add it to the REQUIRE :smile:.

**Comment by lucasb-eyer** [comment]
That, or to the README.md if you want people to always choose their loader.

**Pull request merged**
