### PR TITLE
Fix Test Failures on writemime

### PR DESCRIPTION
**Pull request by mronian**
Fixes test failures for 433cb650516dd4d57807a307c561e6f1b2c6bcff

### CODE REVIEW

**Comment by mronian** [comment]
There are failures on julia-0.4. @timholy What needs to be added?

**Comment by bjarthur** [comment]
ooops, my bad.  i should've run the tests before pushing that change.

i specified an eltype there to get ImageMagick/test/readremote.jl line 116 to succeed.  on that line, `img` is of type `AbstractImage{Colorant}` and was dispatched to the version of `show` on line 36 of Images/src/writemime.jl which inputs `AbstractArray{Colorant}`, the supertype of `AbstractImage{Colorant}`, because the show method on the then line 12 input `AbstractImage` (without the eltype specified).  line 37 then proceeds to pass that `AbstractImage{Colorant}` into `Image` which screwed things up.

would it be better to change the tests as @mronian has done here, or to define show methods for *both* `AbstractImage{Colorant}` and `AbstractImage` ?

**Comment by mronian** [comment]
I think the second way is better? That way it will pass on 0.4 too.

**Comment by timholy** [comment]
Best to do such things as a pull request too; I can no longer count the number of times I've had something pass locally for me, only to discover that I was depending on having checked out the master branch of some package. If other issues didn't cause problems, that might even be relevant here, see https://github.com/JuliaLang/Compat.jl/pull/256 (which has not yet been tagged).

**Comment by timholy** [comment]
Superseded by #521, but thanks so much @mronian for trying to tackle this.

**Pull request closed without merging**
