### PR TITLE
Fixes nnrd output issue #272

### PR DESCRIPTION
**Pull request by cbecker**

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for contributing this!

The Travis failures are nothing for you to worry about: on 0.4 it timed out because of poor performance of FixedPointNumbers where there are deprecation warnings. I just merged the fix I made (https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/19) and am waiting for Travis to approve before I tag the next release.

On 0.3, you got bit by #261 or more clearly the discussion in 7c5fbeebca755807012351bc83e1f7961eefbb69. I just committed a patch to disable that test. Once the FixedPointNumbers things resolves, I'll restart the build here. But Travis is slow and I should leave for the day, so it might not be until tomorrow.

**Comment by cbecker** [comment]
sorry, my mistake, re-opening

**Comment by timholy** [comment]
Passes travis on both 0.3 and 0.4 on Linux; other platforms are simply timing out because of https://github.com/dcjones/Zlib.jl/pull/17. Good enough for me.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
